services:
  - docker
before_install:
  - docker build -t ditransler/cra-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true ditransler/cra-test npm run test
after_success:
  - docker build -t ditransler/multi-docker-fibonacci-calculator-client ./client
  - docker build -t ditransler/multi-docker-fibonacci-calculator-nginx ./nginx
  - docker build -t ditransler/multi-docker-fibonacci-calculator-server ./server
  - docker build -t ditransler/multi-docker-fibonacci-calculator-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take all images and push them to the Docker hub
  - docker push ditransler/multi-docker-fibonacci-calculator-client
  - docker push ditransler/multi-docker-fibonacci-calculator-nginx
  - docker push ditransler/multi-docker-fibonacci-calculator-server
  - docker push ditransler/multi-docker-fibonacci-calculator-worker
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker-fibonacci-calculator
  env: MultiDockerFibonacciCalculator-env
  bucket_name: elasticbeanstalk-us-east-2-958858930604
  bucket_path: multi-docker-fibonacci-calculator
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY