apiVersion: certmanager.k8s.io/v1alpha2
kind: Certificate
metadata:
  name: domain-com-tls
spec:
  secretName: domain-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: domain.com
  dnsNames:
    - domain.com
    - www.domain.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - domain.com
          - www.domain.com